# Generated by Django 5.2.6 on 2025-12-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_remove_review_user_review_old_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='old_username',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_fk',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
